{% set name = "types-Pillow" %}
{% set version = "9.4.0.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Pillow-{{ version }}.tar.gz
  sha256: 7f0e871d2d46fbb6bc7deca3e02dc552cf9c1e8b49deb9595509551be3954e49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/PIL-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Pillow
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
